cors:
  originPatterns: http://localhohost:3000,http://localhost8080,https://www.google.com
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restspringdb?useTimezone=true&serverTimezone=UTC
    username: root
    password: rovidaloka
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui: 
    user-root-path: true